runtime: java11

instance_class: B4
basic_scaling:
  max_instances: 1
  idle_timeout: 60m

service: shared-hash-encrypt-api

env_variables:
  JASYPT_ENCRYPTOR_PASSWORD: '{pick-a-password}'
  JAVA_OPTS: '-Xms384m -Xmx1024m'
  